### ISSUE TITLE
smooth down/up transition for comfy ui

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [SaladTechnologies/comfyui-api#27]
I think would be nice to also provide a guide on how to correctly setup the docker. In particular, how to setup the volumes.

In my case, I'm using
```
version: '3.8'
services:
 comfy:
    image: ghcr.io/saladtechnologies/comfyui-api:comfy0.3.14-api1.8.2-torch2.6.0-cuda12.4-runtime
    container_name: comfy
    ports:
      - "3003:8188"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      - /mnt/disk1/DO_NOT_DELETE/comfyui_stuff/models:/opt/ComfyUI/models
      - /mnt/disk1/DO_NOT_DELETE/comfyui_stuff/output:/opt/ComfyUI/output
      - /mnt/disk1/DO_NOT_DELETE/comfyui_stuff/default:/opt/ComfyUI/user/default
      - /mnt/disk1/DO_NOT_DELETE/comfyui_stuff/custom_nodes:/opt/ComfyUI/custom_nodes
    restart: always
    networks:
      - app-network
```

However, when I take down the container and up again, all the extensions have to be reinstalled (they still exist, but they need the "try fix" from ComfyUI manager)... my guess is that they need the `pip install -r /path/to/requirements.txt`... any idea on how to run it during the build?
